export const Dancelist = [
 	{dict:"anim@amb@nightclub@dancers@solomun_entourage@", anim:"mi_dance_facedj_17_v1_female^1", name:"Dance F"},
 	{dict:"anim@amb@nightclub@mini@dance@dance_solo@female@var_a@", anim:"high_center", name:"Dance F2"},  
 	{dict:"anim@amb@nightclub@mini@dance@dance_solo@female@var_a@", anim:"high_center_up", name:"Dance F3"},
 	{dict:"anim@amb@nightclub@dancers@crowddance_facedj@hi_intensity", anim:"hi_dance_facedj_09_v2_female^1", name:"Dance F4"},
 	{dict:"anim@amb@nightclub@dancers@crowddance_facedj@hi_intensity", anim:"hi_dance_facedj_09_v2_female^3", name:"Dance F5"},
 	{dict:"anim@amb@nightclub@mini@dance@dance_solo@female@var_a@", anim:"high_center_up", name:"Dance F6"},
 	{dict:"anim@amb@nightclub@mini@dance@dance_solo@female@var_a@", anim:"low_center", name:"Dance Slow 2"},  
 	{dict:"anim@amb@nightclub@mini@dance@dance_solo@female@var_a@", anim:"low_center_down", name:"Dance Slow 3"},  
 	{dict:"anim@amb@nightclub@mini@dance@dance_solo@female@var_b@", anim:"low_center", name:"Dance Slow 4"},
 	{dict:"anim@amb@nightclub@dancers@podium_dancers@", anim:"hi_dance_facedj_17_v2_male^5", name:"Dance"},  
 	{dict:"anim@amb@nightclub@mini@dance@dance_solo@male@var_b@", anim:"high_center_down", name:"Dance 2"},  
 	{dict:"anim@amb@nightclub@mini@dance@dance_solo@male@var_a@", anim:"high_center", name:"Dance 3"},
 	{dict:"anim@amb@nightclub@mini@dance@dance_solo@male@var_b@", anim:"high_center_up", name:"Dance 4"},
 	{dict:"anim@amb@nightclub@mini@dance@dance_solo@female@var_b@", anim:"high_center", name:"Dance Upper"},
 	{dict:"anim@amb@nightclub@mini@dance@dance_solo@female@var_b@", anim:"high_center_up", name:"Dance Upper 2"},
 	{dict:"anim@amb@nightclub@mini@dance@dance_solo@male@var_a@", anim:"low_center", name:"Dance Shy"},
 	 {dict:"anim@amb@nightclub@mini@dance@dance_solo@female@var_b@", anim:"low_center_down", name:"Dance Shy 2"},  
 	{dict:"anim@amb@nightclub@mini@dance@dance_solo@male@var_b@", anim:"low_center", name:"Dance Slow"},  
 	{dict:"rcmnigel1bnmt_1b", anim:"dance_loop_tyler", name:"Dance Silly 9"},
 	{dict:"misschinese2_crystalmazemcs1_cs", anim:"dance_loop_tao", name:"Dance 6"},
 	{dict:"misschinese2_crystalmazemcs1_ig", anim:"dance_loop_tao", name:"Dance 7"},
 	{dict:"missfbi3_sniping", anim:"dance_m_default", name:"Dance 8"},
 	{dict:"special_ped@mountain_dancer@monologue_3@monologue_3a", anim:"mnt_dnc_buttwag", name:"Dance Silly"},  
 	{dict:"move_clown@p_m_zero_idles@", anim:"fidget_short_dance", name:"Dance Silly 2"},
 	{dict:"move_clown@p_m_two_idles@", anim:"fidget_short_dance", name:"Dance Silly 3"},
 	{dict:"anim@amb@nightclub@lazlow@hi_podium@", anim:"danceidle_hi_11_buttwiggle_b_laz", name:"Dance Silly 4"},  
 	{dict:"timetable@tracy@ig_5@idle_a", anim:"idle_a", name:"Dance Silly 5"},  
 	{dict:"timetable@tracy@ig_8@idle_b", anim:"idle_d", name:"Dance Silly 6"},  
 	{dict:"anim@amb@nightclub@mini@dance@dance_solo@female@var_a@", anim:"med_center_up", name:"Dance 9"},  
 	{dict:"anim@mp_player_intcelebrationfemale@the_woogie", anim:"the_woogie", name:"Dance Silly 8"},  
 	{dict:"anim@amb@casino@mini@dance@dance_solo@female@var_b@", anim:"high_center", name:"Dance Silly 7"},
 	{dict:"anim@amb@casino@mini@dance@dance_solo@female@var_a@", anim:"med_center", name:"Dance 5"},
 ];
 
 
 
 export const Actionlist = [
	{dict:"anim@arena@celeb@flat@solo@props@", anim:"make_it_rain_b_player_b", name:"Make it Rain", EmoteDuration:300000},  
	{dict:"anim@mp_player_intcelebrationfemale@air_guitar", anim:"air_guitar", name:"Air Guitar", EmoteDuration:300000},  
    {dict:"anim@mp_player_intcelebrationfemale@air_synth", anim:"air_synth", name:"Air Synth", EmoteDuration:300000}, 
    {dict:"anim@mp_player_intcelebrationfemale@blow_kiss", anim:"blow_kiss", name:"Blow Kiss", EmoteDuration:2000 },
 {dict:"anim@mp_player_intselfieblow_kiss", anim:"exit", name:"Blow Kiss 2", EmoteDuration:2000 },
  {dict:"anim@mp_player_intcelebrationfemale@face_palm", anim:"face_palm", name:"Facepalm 2",EmoteDuration:8000  },
 {dict:"anim@mp_player_intupperface_palm", anim:"idle_a", name:"Facepalm 4", EmoteDuration:300000  },
  {dict:"anim@mp_player_intselfiethe_bird", anim:"idle_a", name:"Finger", EmoteDuration:300000},
 {dict:"anim@mp_player_intupperfinger", anim:"idle_a_fp", name:"Finger 2", EmoteDuration:300000},
 {dict:"mp_ped_interaction", anim:"handshake_guy_a", name:"Handshake", EmoteDuration:3000  },
 {dict:"mp_ped_interaction", anim:"handshake_guy_b", name:"Handshake 2", EmoteDuration:3000  },
 {dict:"anim@mp_player_intcelebrationfemale@jazz_hands", anim:"jazz_hands", name:"Jazzhands", EmoteDuration:6000},
 {dict:"anim@mp_player_intcelebrationfemale@knuckle_crunch", anim:"knuckle_crunch", name:"Knuckle Crunch", EmoteDuration:300000},
 {dict:"mp_player_int_upper_nod", anim:"mp_player_int_nod_no", name:"No 2", EmoteDuration:300000},
 {dict:"anim@mp_player_intcelebrationfemale@nose_pick", anim:"nose_pick", name:"Nose Pick", EmoteDuration:300000},
 {dict:"gestures@m@standing@casual", anim:"gesture_no_way", name:"No Way", EmoteDuration:1500,  },  
 {dict:"anim@mp_player_intselfiedock", anim:"idle_a", name:"OK", EmoteDuration:300000},
 {dict:"mp_gun_shop_tut", anim:"indicate_right", name:"Point Right", EmoteDuration:300000},
 {dict:"anim@mp_player_intincarsalutestd@ds@", anim:"idle_a", name:"Salute", EmoteDuration:300000},
 {dict:"anim@mp_player_intincarsalutestd@ps@", anim:"idle_a", name:"Salute 2", EmoteDuration:300000},
 {dict:"anim@mp_player_intuppersalute", anim:"idle_a", name:"Salute 3", EmoteDuration:300000},
  {dict:"anim@mp_player_intupperslow_clap", anim:"idle_a", name:"Slow Clap 3", EmoteDuration:300000},
 {dict:"amb@world_human_cheering@male_a", anim:"base", name:"Clap", EmoteDuration:300000},
 {dict:"anim@mp_player_intcelebrationfemale@slow_clap", anim:"slow_clap", name:"Slow Clap", EmoteDuration:300000},
 {dict:"anim@mp_player_intcelebrationmale@slow_clap", anim:"slow_clap", name:"Slow Clap 2", EmoteDuration:300000},
 {dict:"mp_cp_welcome_tutthink", anim:"b_think", name:"Think 5", EmoteDuration:2000,  },
 {dict:"anim@mp_player_intincarthumbs_uplow@ds@", anim:"enter", name:"Thumbs Up 3", EmoteDuration:3000,  },
 {dict:"anim@mp_player_intselfiethumbs_up", anim:"idle_a", name:"Thumbs Up 2", EmoteDuration:300000},
 {dict:"anim@mp_player_intupperthumbs_up", anim:"idle_a", name:"Thumbs Up", EmoteDuration:300000},
 {dict:"anim@mp_player_intcelebrationfemale@wave", anim:"wave", name:"Wave 2", EmoteDuration:300000},
 {dict:"friends@fra@ig_1", anim:"over_here_idle_a", name:"Wave 3", EmoteDuration:300000},
 {dict:"gestures@m@standing@casual", anim:"gesture_hello", name:"Wave 9", EmoteDuration:300000},
 {dict:"taxi_hail", anim:"hail_taxi", name:"Whistle", EmoteDuration:1300},
 {dict:"anim@mp_player_intupperair_shagging", anim:"idle_a", name:"Yeah", EmoteDuration:300000},
  {dict:"mp_player_int_uppergang_sign_a", anim:"mp_player_int_gang_sign_a", name:"Gang Sign", EmoteDuration:300000},
 {dict:"mp_player_int_uppergang_sign_b", anim:"mp_player_int_gang_sign_b", name:"Gang Sign 2", EmoteDuration:300000},
  {dict:"anim@mp_player_intmenu@key_fob@", anim:"fob_click", name:"Key Fob", EmoteDuration:1000},
 {dict:"mp_player_inteat@burger", anim:"mp_player_int_eat_burger", name:"Eat", EmoteDuration:3000},
  {dict:"anim@mp_player_intupperfind_the_fish", anim:"idle_a", name:"Fish Dance", EmoteDuration:300000},
 {dict:"mp_player_int_upperpeace_sign", anim:"mp_player_int_peace_sign", name:"Peace", EmoteDuration:300000},
 {dict:"anim@mp_player_intupperpeace", anim:"idle_a", name:"Peace 2", EmoteDuration:300000},
  {dict:"rcmextreme2", anim:"loop_punching", name:"Punching", EmoteDuration:300000},
 {dict:"rcmbarry", anim:"base", name:"Superhero", EmoteDuration:300000  },
 {dict:"rcmbarry", anim:"base", name:"Superhero 2", EmoteDuration:300000},
 {dict:"rcmbarry", anim:"mind_control_b_loop", name:"Mind Control", EmoteDuration:300000  },
 {dict:"rcmbarry", anim:"bar_1_attack_idle_aln", name:"Mind Control 2", EmoteDuration:300000  },
  {dict:"timetable@amanda@ig_4", anim:"ig_4_base", name:"Namaste", EmoteDuration:300000},  
 {dict:"anim@amb@nightclub@djs@dixon@", anim:"dixn_dance_cntr_open_dix", name:"DJ", EmoteDuration:300000},
 {dict:"random@peyote@bird", anim:"wakeup", name:"Bird", EmoteDuration:300000},
 {dict:"random@peyote@chicken", anim:"wakeup", name:"Chicken", EmoteDuration:300000},
 {dict:"missminuteman_1ig_2", anim:"handsup_base", name:"Hands Up", EmoteDuration:300000  },
];